import type { Metadata } from "next";
import "./globals.css";
import { Libre_Baskerville, IBM_Plex_Mono, Lora } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const libre = Libre_Baskerville({
  weight: ["400", "700"],
  variable: "--font-libre-baskerville",
  display: "swap",
});

const mono = IBM_Plex_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-ibm-mono",
  display: "swap",
});

const serif = Lora({
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libre.variable} ${mono.variable} ${serif.variable} antialiased dark font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
