import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Geist_Mono, Libre_Baskerville, Lora } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mocha Chat",
  description: "Generated by create next app",
};

const libre = Libre_Baskerville({
  weight: ["400", "700"],
  variable: "--font-libre-baskerville",
  display: "swap",
  subsets: ["latin"],
});

const mono = Geist_Mono({
  weight: ["500"],
  variable: "--font-geist-mono",
  display: "swap",
  subsets: ["latin"],
});

const serif = Lora({
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
  display: "swap",
  subsets: ["cyrillic"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <script src="https://unpkg.com/react-scan/dist/auto.global.js" />
      </head> */}
      <body
        className={`${libre.variable} ${mono.variable} ${serif.variable} antialiased dark font-sans`}
      >
        <SidebarProvider>{children}</SidebarProvider>
      </body>
    </html>
  );
}
